@{
	RootModule = 'NETX.YouTrack.psm1'
	ModuleVersion = '1.2.3.0'
	GUID = '7da613c6-8770-4cef-a8d8-89cde68d4753'
	Author = 'NET-Experts'
	CompanyName = 'NET-Experts'
	Copyright = '(c) NET-Experts. All rights reserved.'
	Description = 'NET-Experts PowerShell Support for JetBrains YouTrack Rest API'
	PowerShellVersion = '4.0'
	CLRVersion = '4.0'
	FunctionsToExport = '*'
	CmdletsToExport = '*'
	VariablesToExport = '*'
	AliasesToExport = '*'
}
